name: Streamlit Docker Build and Deploy

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
    
    - uses: actions/checkout@v1
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

    # Deploy to server (optional)
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest
          docker stop streamlit-container || true
          docker rm streamlit-container || true
          docker run -d --name streamlit-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

  
