name: Streamlit Docker Build and Deploy

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
    
    - uses: actions/checkout@v1
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Run Docker Image
      run: |
        docker run -p 80:80 5c6442ae4997

  
